apiVersion: v1
kind: Service
metadata:
  name: cadvisor-service
  namespace: cadvisor
  labels: 
    name: cadvisor
spec:
  selector:
    name: cadvisor
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 30039
    protocol: TCP